
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Number of Sites and Threshold Values we want to simulate
NUM_SITES = {31622,10000, 3162,1000,}
THRES = {1, 5, 10, 30, 100}

#Rule for a test run of the simulation to 
rule get_data:
	input:
		"simulation.slim"
	output:
		expand(["{L}_{T}_test.txt"], L = NUM_SITES, T=THRES)
	run:
		for i in NUM_SITES:
			for t in THRES:
				shell('slim -d envVar=0.05 -d adjustment=0 -d L={i} -d thres={t} {input}')


#Rule to calculate the environmental variance and liability adjustment that goes into the real simulation
rule calc_vals:
	input:
		expand(["{L}_{T}_test.txt"], L = NUM_SITES, T=THRES)
	output:
		expand(["{L}_{T}_data.txt"], L = NUM_SITES, T=THRES)
	run:
		for i in NUM_SITES:
			for t in THRES:
				data = pd.read_csv(str(str(i) +"_" + str(t) + "_test.txt"), sep=" ", header=None)
				env_var = data.iloc[20000:30000,0].mean()
				liability = data.iloc[5000:10000, 1].mean()				
				with open((str(i) +"_" + str(t) + "_data.txt"), "w") as out:
					out.write("{}\n{}".format(str(env_var), str(liability)))

#Rule to run the simulations with the environmental variance and liability adjustment from the test simulation
rule run_sims:
	input:
		expand(["{L}_{T}_data.txt"], L = NUM_SITES, T=THRES)
	output:
		expand(["{L}_{T}.txt"], L = NUM_SITES, T=THRES)
	run:
		for i in NUM_SITES:
			for t in THRES:
				shell("declare var=$(sed -n '1p' {input}) declare adj=$(sed -n '2p' {input}); slim -d envVar=$var -d adjustment=$adj -d L={i} -d thres={t} simulation.slim")


#Rule that analyzes each simulation and finds average value of Heritability, Genetic Variance, Prevalance, Risk Effect and Mean Liability
rule analyze:
	input:
		expand(["{L}_{T}.txt"], L = NUM_SITES, T=THRES)
	output:
		expand(["{L}_{T}_analysis.txt"], L = NUM_SITES, T=THRES)
	run:
		for i in NUM_SITES:
			for t in THRES:
				name = str(i) + "_" + str(t)
				df = pd.read_csv((str(i) +"_" + str(t) + ".txt"), sep=" ", header=i, names=["Heritability", "Genetic Variance", "Prevalance", "Risk", "Mean Liability"])
				data = df.mean()
				data.to_csv(name+ "_analysis.txt")


#Rule that combines all the analysis from simulations into one dataframe
rule summary:
	input:
		expand(["{L}_{T}_analysis.txt"], L = NUM_SITES, T=THRES)
	output:
		"summary.csv"
	run:
		d = 0
		summary = pd.DataFrame(columns=["Heritability", "Genetic Variance", "Prevalance", "Risk", "Mean Liability", "Threshold", "Number Sites"])
		for i in NUM_SITES:
			for t in THRES:
				name = str(i) + "_" + str(t)
				df = pd.read_csv((str(i) +"_" + str(t) + "_analysis.txt"), sep=",", header=0, index_col = 0)
				df_t = df.T
				df_t.index_col = str(t)
				df_t = df_t.rename(index = {"0":name})
				df_t["Threshold"] = t
				df_t["Number Sites"] = i
				summary = pd.concat([summary,df_t], axis=0)
		summary.to_csv("summary.csv")


#Rule that plots everything
rule plot:
	input:
		"summary.csv"
	output:
		"plot.png"
	run:
		df = pd.read_csv("summary.csv", sep=",", header=0, index_col = 0)
		groups = df.sort_values(by=['Number Sites'], ascending=False).groupby("Threshold")
		markers = ["o", "v", "*", "p"]
		colors = ["red", "blue", "orange", "yellow", "green"]

		j = 0
		for name, group in groups:
		    plt.scatter(group["Number Sites"], group["Prevalance"], marker="o", label=name, color=colors[j])
		    j += 1
		plt.legend(title="Threshold Value")
		plt.savefig('Prev_plot.png')

		fig, ax = plt.subplots()
		j = 0
		for name, group in groups:
			for i in markers:
				#assign different value to every Number of Site and a color for every threshold value 
				scatter = ax.scatter(group["Risk"], group["Prevalance"], marker=i, label=name, color=colors[j])
			j += 1

		handles1 = [plt.scatter([0], [0], marker="o", color = c) for c in colors]
		handles2 = [plt.scatter([0], [0], marker=c, color ="black") for c in markers]

		legend1= ax.legend(handles1,[THRES], title ="Threshold", loc="center right")
		legend2 = ax.legend(handles2,[NUM_SITES], title ="Number of Sites", loc="lower right")
		ax.add_artist(legend1)
		ax.add_artist(legend2)
		plt.savefig('Risk_plot.png')





